---
title: "data-clean"
output: html_document
---

```{r}
library(tidyverse)
brain = read.csv("brain.csv")
```

```{r}
sum(is.na(brain))
```

```{r}
sample=sample.int(n = nrow(brain), size = floor(.50*nrow(brain)), replace = F)

train=brain[sample, ]
test=brain[-sample, ]
```


```{r}
library(e1071)

naive_bayes_model = naiveBayes(x = train[,3:54677], y = train[,2])
svm_linear_model = svm(x = train[,3:54677], y = train[,2], kernel = "linear")
svm_nonlinear_model = svm(x = train[,3:54677], y = train[,2], kernel = "radial")
```


```{r}
nb_pred = predict(naive_bayes_model, test[,3:54677])
svm_linear_pred = predict(svm_linear_model, test[,3:54677])
svm_nonlinear_pred = predict(svm_nonlinear_model, test[,3:54677])

```


```{r}

model_predictions = data.frame(
  samples = test$samples,
  actual = test$type,
  svm_linear_pred = svm_linear_pred,
  svm_nonlinear_pred = svm_nonlinear_pred,
  nb_pred = nb_pred
)


```

```{r}
library(caret)

svm_linear_confusionMatrix = confusionMatrix(model_predictions$svm_linear_pred, model_predictions$actual)
svm_linear_confusionMatrix

svm_nonlinear_confusionMatrix = confusionMatrix(model_predictions$svm_nonlinear_pred ,model_predictions$actual)
svm_nonlinear_confusionMatrix

nb_confusionMatrix = confusionMatrix(model_predictions$nb_pred,model_predictions$actual)
nb_confusionMatrix
```





